import { useState, useEffect } from 'react'
import { useLocation } from 'react-router-dom'
import ElderLayout from '../../components/layout/ElderLayout'
import VitalInput from '../../components/health/VitalInput'
import MoodSelector from '../../components/health/MoodSelector'
import BPTrendChart from '../../components/health/BPTrendChart'
import SugarTrendChart from '../../components/health/SugarTrendChart'
import WeightTrendChart from '../../components/health/WeightTrendChart'
import MoodTrendRow from '../../components/health/MoodTrendRow'
import { supabase } from '../../lib/supabase'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000'

function todayLabel() {
  return new Date().toLocaleDateString('en-IN', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  })
}

const MOOD_EMOJI = { very_happy: '😄', happy: '😊', okay: '😐', sad: '😔', unwell: '😞' }

/* ─── Status border color helper ──────────────────── */
function entryBorderColor(log) {
  if (!log.bp_systolic && !log.bp_diastolic && !log.sugar_level && !log.weight) return '#DDE8F5'
  const bpHigh = log.bp_systolic > 140 || log.bp_diastolic > 90
  const bpElevated = log.bp_systolic > 130 || log.bp_diastolic > 85
  const sugarHigh = log.sugar_level > 180
  const sugarElevated = log.sugar_level > 125
  if (bpHigh || sugarHigh) return '#E24B4A'
  if (bpElevated || sugarElevated) return '#BA7517'
  return '#1D9E75'
}

/* ─── History & Trends tab ─────────────────────────── */
function HistoryTab({ userId, switchToLog }) {
  const [period, setPeriod]       = useState('7')
  const [trendData, setTrendData] = useState([])
  const [logs, setLogs]           = useState([])
  const [loadingTrend, setLoadingTrend] = useState(true)
  const [loadingLogs, setLoadingLogs]   = useState(true)

  // Summary state
  const [summary, setSummary]           = useState(null)
  const [summaryLoading, setSummaryLoading] = useState(false)
  const [summaryError, setSummaryError]     = useState(null)
  const [summaryOpen, setSummaryOpen]       = useState(false)
  const [copyLabel, setCopyLabel]           = useState('Copy Text')

  const PERIODS = [
    { label: '7 Days',   value: '7' },
    { label: '30 Days',  value: '30' },
    { label: 'All Time', value: '365' },
  ]

  useEffect(() => {
    if (!userId) return
    setLoadingTrend(true)
    fetch(`${API_URL}/api/health/trend/${userId}?days=${period}`)
      .then(r => r.json())
      .then(d => setTrendData(d.data || []))
      .catch(() => setTrendData([]))
      .finally(() => setLoadingTrend(false))
  }, [userId, period])

  useEffect(() => {
    if (!userId) return
    fetch(`${API_URL}/api/health/history/${userId}`)
      .then(r => r.json())
      .then(d => setLogs(d.logs || []))
      .catch(() => {})
      .finally(() => setLoadingLogs(false))
  }, [userId])

  async function generateSummary() {
    setSummaryLoading(true)
    setSummaryError(null)
    setSummary(null)
    setSummaryOpen(false)
    try {
      const res = await fetch(`${API_URL}/api/health/summary/${userId}`)
      if (res.status === 429) {
        setSummaryError('Sahara is busy right now. Please try generating the summary again in a moment.')
        return
      }
      const data = await res.json()
      if (!data.success) throw new Error(data.error || 'Failed')
      setSummary(data)
      setSummaryOpen(true)
    } catch (e) {
      setSummaryError(e.message || 'Could not generate summary. Please try again.')
    } finally {
      setSummaryLoading(false)
    }
  }

  function copySummary() {
    if (!summary) return
    const text = [
      `Patient: ${summary.patientName || 'Unknown'}, Age: ${summary.patientAge || 'Unknown'}`,
      summary.conditions?.length ? `Conditions: ${summary.conditions.join(', ')}` : '',
      '',
      summary.summary,
      '',
      `Generated by Sahara Health — ${new Date().toLocaleDateString('en-IN')}`,
    ].filter(l => l !== undefined).join('\n')
    navigator.clipboard.writeText(text).then(() => {
      setCopyLabel('Copied!')
      setTimeout(() => setCopyLabel('Copy Text'), 2000)
    })
  }

  function shareSummary() {
    if (!summary) return
    const text = `${summary.patientName || 'Patient'} Health Summary\n\n${summary.summary}\n\nGenerated by Sahara Health`
    if (navigator.share) {
      navigator.share({ title: 'Health Summary', text })
    } else {
      copySummary()
    }
  }

  // Mood-only data always last 7 days
  const moodData7 = trendData.filter((_, i, arr) => {
    // if period is 7 already, use full trendData; otherwise we need last 7
    return true
  })

  return (
    <div>
      {/* Period selector */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 20 }}>
        {PERIODS.map(p => {
          const active = period === p.value
          return (
            <button
              key={p.value}
              onClick={() => setPeriod(p.value)}
              style={{
                flex: 1, height: 36, borderRadius: 20,
                border: active ? '2px solid #1D9E75' : '1.5px solid #DDE8F5',
                background: active ? '#1D9E75' : 'white',
                color: active ? 'white' : '#5A7A9A',
                fontSize: 13, fontWeight: 700, cursor: 'pointer',
                fontFamily: 'inherit', transition: 'all 0.15s',
              }}
            >
              {p.label}
            </button>
          )
        })}
      </div>

      {/* Charts */}
      {loadingTrend ? (
        <div style={{ textAlign: 'center', padding: 40, color: '#A0B8D0' }}>
          <i className="ti ti-loader-2" style={{ fontSize: 24, display: 'block', marginBottom: 8 }} />
          Loading trends…
        </div>
      ) : (
        <>
          <BPTrendChart     data={trendData.filter(d => d.systolic  != null)} />
          <SugarTrendChart  data={trendData.filter(d => d.sugar     != null)} />
          <WeightTrendChart data={trendData.filter(d => d.weight    != null)} />
          <MoodTrendRow data={trendData} />
        </>
      )}

      {/* Share with Doctor */}
      <p style={{ fontSize: 16, fontWeight: 700, color: '#0A2540', marginBottom: 12 }}>Share with Doctor</p>
      <div style={{
        background: '#EBF4FF', border: '1.5px solid #DDE8F5',
        borderRadius: 16, padding: 16, marginBottom: 24,
      }}>
        <button
          onClick={generateSummary}
          disabled={summaryLoading}
          style={{
            display: 'flex', alignItems: 'center', gap: 8,
            height: 44, padding: '0 20px', borderRadius: 12,
            border: '2px solid #1D9E75', background: 'white',
            color: '#1D9E75', fontSize: 14, fontWeight: 700,
            cursor: summaryLoading ? 'not-allowed' : 'pointer',
            fontFamily: 'inherit', opacity: summaryLoading ? 0.7 : 1,
          }}
        >
          <i className="ti ti-file-text" style={{ fontSize: 16 }} />
          {summaryLoading ? 'Generating summary…' : 'Generate AI Summary'}
        </button>

        {summaryError && (
          <div style={{
            marginTop: 12, background: '#FFF4F4', border: '1px solid #FECACA',
            borderRadius: 10, padding: '10px 14px', color: '#E24B4A',
            fontSize: 13, fontWeight: 600,
          }}>
            <i className="ti ti-alert-circle" style={{ marginRight: 6 }} />
            {summaryError}
          </div>
        )}

        {summary && summaryOpen && (
          <div style={{
            marginTop: 14, background: 'white', border: '1.5px solid #DDE8F5',
            borderRadius: 14, padding: 16,
          }}>
            <p style={{ fontSize: 13, fontWeight: 700, color: '#0A2540', marginBottom: 2 }}>
              {summary.patientName || 'Patient'}
              {summary.patientAge ? `, Age ${summary.patientAge}` : ''}
            </p>
            {summary.conditions?.length > 0 && (
              <p style={{ fontSize: 11, color: '#5A7A9A', marginBottom: 10 }}>
                Conditions: {summary.conditions.join(', ')}
              </p>
            )}
            <p style={{ fontSize: 13, color: '#0A2540', lineHeight: 1.65, marginBottom: 12 }}>
              {summary.summary}
            </p>
            <p style={{ fontSize: 11, color: '#A0B8D0', marginBottom: 14 }}>
              Generated on {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
            </p>
            <div style={{ display: 'flex', gap: 10 }}>
              <button
                onClick={copySummary}
                style={{
                  flex: 1, height: 40, borderRadius: 10,
                  border: '1.5px solid #DDE8F5', background: 'white',
                  color: '#185FA5', fontSize: 13, fontWeight: 700,
                  cursor: 'pointer', fontFamily: 'inherit',
                }}
              >
                <i className="ti ti-copy" style={{ marginRight: 6 }} />{copyLabel}
              </button>
              <button
                onClick={shareSummary}
                style={{
                  flex: 1, height: 40, borderRadius: 10,
                  border: '1.5px solid #DDE8F5', background: 'white',
                  color: '#185FA5', fontSize: 13, fontWeight: 700,
                  cursor: 'pointer', fontFamily: 'inherit',
                }}
              >
                <i className="ti ti-share" style={{ marginRight: 6 }} />Share
              </button>
            </div>
          </div>
        )}
      </div>

      {/* All Entries history list */}
      <p style={{ fontSize: 16, fontWeight: 700, color: '#0A2540', marginTop: 24, marginBottom: 12 }}>All Entries</p>

      {loadingLogs ? (
        <div style={{ textAlign: 'center', padding: 32, color: '#A0B8D0' }}>
          <i className="ti ti-loader-2" style={{ fontSize: 24, display: 'block', marginBottom: 8 }} />
          Loading…
        </div>
      ) : !logs.length ? (
        <div style={{ textAlign: 'center', padding: '40px 0' }}>
          <i className="ti ti-heart-rate-monitor" style={{ fontSize: 48, color: '#DDE8F5', display: 'block', marginBottom: 12 }} />
          <p style={{ fontSize: 16, fontWeight: 600, color: '#5A7A9A', marginBottom: 6 }}>No health logs yet</p>
          <p style={{ fontSize: 14, color: '#A0B8D0', marginBottom: 20 }}>Start tracking your health today</p>
          <button
            onClick={switchToLog}
            style={{
              height: 44, padding: '0 24px', borderRadius: 12,
              background: '#1D9E75', border: 'none', color: 'white',
              fontSize: 15, fontWeight: 700, cursor: 'pointer', fontFamily: 'inherit',
            }}
          >
            Log Today
          </button>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, paddingBottom: 24 }}>
          {logs.map(log => (
            <div
              key={log.id}
              style={{
                background: 'white', border: '1.5px solid #DDE8F5',
                borderLeft: `3px solid ${entryBorderColor(log)}`,
                borderRadius: 12, padding: '12px 14px',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                <span style={{ fontSize: 13, fontWeight: 700, color: '#0A2540' }}>
                  {new Date(log.logged_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
                </span>
                <span style={{ fontSize: 11, color: '#A0B8D0' }}>
                  {new Date(log.logged_at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
                </span>
                {log.mood && <span style={{ marginLeft: 'auto', fontSize: 18 }}>{MOOD_EMOJI[log.mood]}</span>}
              </div>
              <p style={{ fontSize: 12, color: '#5A7A9A', lineHeight: 1.8 }}>
                {[
                  log.bp_systolic && log.bp_diastolic ? `BP ${log.bp_systolic}/${log.bp_diastolic}` : null,
                  log.sugar_level ? `Sugar ${log.sugar_level}` : null,
                  log.weight      ? `Weight ${log.weight}kg`   : null,
                ].filter(Boolean).join(' · ')}
              </p>
              {log.notes && (
                <p style={{ fontSize: 11, color: '#A0B8D0', fontStyle: 'italic', marginTop: 4 }}>{log.notes}</p>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

/* ─── Log Today tab ────────────────────────────────── */
function LogTodayTab({ userId, onSaveSuccess }) {
  const location = useLocation()
  const [systolic,  setSystolic]  = useState('')
  const [diastolic, setDiastolic] = useState('')
  const [sugar,     setSugar]     = useState('')
  const [weight,    setWeight]    = useState('')
  const [mood,      setMood]      = useState('')
  const [notes,     setNotes]     = useState('')

  const [todayCount,  setTodayCount]  = useState(0)
  const [checkDone,   setCheckDone]   = useState(false)
  const [saving,      setSaving]      = useState(false)
  const [error,       setError]       = useState(null)
  const [aiTip,       setAiTip]       = useState(null)
  const [warning,     setWarning]     = useState(null)
  const [showSuccess, setShowSuccess] = useState(false)

  // Pre-fill from companion vitals handoff
  useEffect(() => {
    if (location.state?.prefillVitals) {
      const v = location.state.prefillVitals
      if (v.systolic)  setSystolic(String(v.systolic))
      if (v.diastolic) setDiastolic(String(v.diastolic))
      if (v.sugar)     setSugar(String(v.sugar))
      if (v.weight)    setWeight(String(v.weight))
    }
  }, [location.state])

  // Count how many readings logged today
  useEffect(() => {
    if (!userId) return
    const today = new Date()
    today.setHours(0, 0, 0, 0)
    fetch(`${API_URL}/api/health/history/${userId}?limit=50`)
      .then(r => r.json())
      .then(d => {
        const count = (d.logs || []).filter(l =>
          new Date(l.logged_at) >= today
        ).length
        setTodayCount(count)
        setCheckDone(true)
      })
      .catch(() => setCheckDone(true))
  }, [userId, showSuccess])

  const allEmpty = !systolic && !diastolic && !sugar && !weight && !mood

  async function handleSave() {
    if (allEmpty) return
    setSaving(true); setError(null); setAiTip(null); setWarning(null)
    try {
      const res = await fetch(`${API_URL}/api/health/log`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          elder_id:     userId,
          bp_systolic:  systolic  ? parseFloat(systolic)  : null,
          bp_diastolic: diastolic ? parseFloat(diastolic) : null,
          sugar_level:  sugar     ? parseFloat(sugar)     : null,
          weight:       weight    ? parseFloat(weight)    : null,
          mood:         mood      || null,
          notes:        notes     || null,
        }),
      })
      if (res.status === 429) { setError('Sahara is busy. Please wait a moment and try saving again.'); return }
      const data = await res.json()
      if (!data.success) throw new Error(data.error || 'Save failed')
      if (data.log?.ai_tip) setAiTip(data.log.ai_tip)
      if (data.warning)     setWarning(data.warning)
      setShowSuccess(true)
      setSystolic(''); setDiastolic(''); setSugar(''); setWeight(''); setMood(''); setNotes('')
      setTimeout(() => { setShowSuccess(false); onSaveSuccess() }, 3000)
    } catch (e) {
      setError(e.message || 'Something went wrong. Please try again.')
    } finally {
      setSaving(false)
    }
  }

  if (!checkDone) return (
    <div style={{ textAlign: 'center', padding: 48, color: '#A0B8D0' }}>
      <i className="ti ti-loader-2" style={{ fontSize: 28, display: 'block', marginBottom: 8 }} />Loading…
    </div>
  )

  return (
    <div>
      <div style={{ marginBottom: 20, display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
        <div>
          <h2 style={{ fontSize: 22, fontWeight: 700, color: '#0A2540', marginBottom: 4 }}>How are you today?</h2>
          <p style={{ fontSize: 14, color: '#A0B8D0' }}>{todayLabel()}</p>
        </div>
        {todayCount > 0 && (
          <div style={{ background: '#EBF4FF', border: '1.5px solid #DDE8F5', borderRadius: 20, padding: '4px 12px', fontSize: 12, fontWeight: 700, color: '#185FA5', whiteSpace: 'nowrap', marginTop: 4 }}>
            <i className="ti ti-check" style={{ marginRight: 4 }} />
            {todayCount} reading{todayCount > 1 ? 's' : ''} today
          </div>
        )}
      </div>

      {showSuccess && (
        <div style={{ textAlign: 'center', padding: '16px 0', marginBottom: 16 }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 56, height: 56, borderRadius: '50%', background: '#F0FBF7', border: '2px solid #1D9E75', animation: 'scaleIn 0.3s ease', marginBottom: 8 }}>
            <i className="ti ti-check" style={{ fontSize: 28, color: '#1D9E75' }} />
          </div>
          <p style={{ fontSize: 14, fontWeight: 700, color: '#0F6E56' }}>Reading saved! You can log another anytime.</p>
        </div>
      )}

      {aiTip && (
        <div style={{ background: '#FFFBEB', border: '1px solid #FDE68A', borderRadius: 12, padding: '12px 14px', marginBottom: 14, display: 'flex', gap: 10, alignItems: 'flex-start' }}>
          <i className="ti ti-bulb" style={{ fontSize: 20, color: '#BA7517', flexShrink: 0, marginTop: 1 }} />
          <p style={{ fontSize: 13, color: '#92400E', lineHeight: 1.6 }}>{aiTip}</p>
        </div>
      )}

      {warning && (
        <div style={{ background: '#FFF4F4', border: '1px solid #FECACA', borderRadius: 12, padding: '12px 14px', marginBottom: 14 }}>
          <div style={{ display: 'flex', gap: 8, alignItems: 'flex-start', marginBottom: 6 }}>
            <i className="ti ti-alert-triangle" style={{ fontSize: 18, color: '#E24B4A', flexShrink: 0, marginTop: 1 }} />
            <p style={{ fontSize: 13, fontWeight: 700, color: '#E24B4A' }}>{warning.message}</p>
          </div>
          <p style={{ fontSize: 11, color: '#9B1C1C', marginLeft: 26 }}>This is not a diagnosis. Please consult a doctor if you are concerned.</p>
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div style={{ display: 'flex', gap: 10 }}>
            <div style={{ flex: 1 }}>
              <VitalInput label="SYSTOLIC" unit="mmHg" placeholder="120" icon="ti-heart-rate-monitor" iconColor="#E24B4A" value={systolic} onChange={setSystolic} min={40} max={300} />
            </div>
            <div style={{ flex: 1 }}>
              <VitalInput label="DIASTOLIC" unit="mmHg" placeholder="80" icon="ti-heart-rate-monitor" iconColor="#E24B4A" value={diastolic} onChange={setDiastolic} min={30} max={200} />
            </div>
          </div>
          <VitalInput label="BLOOD SUGAR" unit="mg/dL" placeholder="100" icon="ti-droplet" iconColor="#BA7517" value={sugar} onChange={setSugar} min={20} max={600} />
          <VitalInput label="WEIGHT" unit="kg" placeholder="65" icon="ti-scale" iconColor="#185FA5" value={weight} onChange={setWeight} min={20} max={300} step={0.5} />
          <div>
            <p style={{ fontSize: 13, fontWeight: 700, color: '#5A7A9A', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 10 }}>How are you feeling?</p>
            <MoodSelector selected={mood} onChange={setMood} />
          </div>
          <textarea rows={3} value={notes} onChange={e => setNotes(e.target.value)} placeholder="Any symptoms or notes? (optional)" style={{ width: '100%', border: '1.5px solid #DDE8F5', borderRadius: 16, padding: 12, fontSize: 14, color: '#0A2540', background: 'white', fontFamily: 'inherit', resize: 'vertical', outline: 'none', boxSizing: 'border-box' }} />
          {error && (
            <div style={{ background: '#FFF4F4', border: '1px solid #FECACA', borderRadius: 10, padding: '10px 14px', color: '#E24B4A', fontSize: 13, fontWeight: 600 }}>
              <i className="ti ti-alert-circle" style={{ marginRight: 6 }} />{error}
            </div>
          )}
          <button onClick={handleSave} disabled={allEmpty || saving} style={{ width: '100%', height: 56, borderRadius: 14, background: allEmpty || saving ? '#A0B8D0' : '#1D9E75', border: 'none', color: 'white', fontSize: 18, fontWeight: 700, cursor: allEmpty || saving ? 'not-allowed' : 'pointer', fontFamily: 'inherit', transition: 'background 0.15s' }}>
            {saving ? 'Saving…' : "Save Reading"}
          </button>
        </div>
      <style>{`@keyframes scaleIn { from { transform: scale(0.5); opacity: 0 } to { transform: scale(1); opacity: 1 } }`}</style>
    </div>
  )
}

/* ─── Main page ────────────────────────────────────── */
export default function ElderHealth() {
  const [activeTab, setActiveTab] = useState('log')
  const [userId, setUserId]       = useState(null)
  const location = useLocation()

  useEffect(() => {
    // If companion hands off vitals, make sure we're on the log tab
    if (location.state?.prefillVitals) setActiveTab('log')
  }, [location.state])

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (!session) { window.location.href = '/login'; return }
      setUserId(session.user.id)
    })
  }, [])

  const TABS = [
    { key: 'log',     label: 'Log Today' },
    { key: 'history', label: 'History & Trends' },
  ]

  return (
    <ElderLayout>
      <div style={{ display: 'flex', borderBottom: '2px solid #DDE8F5', marginBottom: 24 }}>
        {TABS.map(tab => {
          const active = activeTab === tab.key
          return (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              style={{
                flex: 1, height: 48, border: 'none', background: 'transparent',
                cursor: 'pointer', fontFamily: 'inherit',
                fontSize: 15, fontWeight: 700,
                color: active ? '#1D9E75' : '#A0B8D0',
                borderBottom: active ? '2px solid #1D9E75' : '2px solid transparent',
                marginBottom: -2, transition: 'all 0.15s',
              }}
            >
              {tab.label}
            </button>
          )
        })}
      </div>

      {activeTab === 'log'
        ? <LogTodayTab userId={userId} onSaveSuccess={() => setActiveTab('history')} />
        : <HistoryTab  userId={userId} switchToLog={() => setActiveTab('log')} />
      }
    </ElderLayout>
  )
}
