require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') })
const { createClient } = require('@supabase/supabase-js')

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SECRET_KEY
)

// ─────────────────────────────────────────────
// GUIDE DEFINITIONS
// ─────────────────────────────────────────────

const guides = [
  // ── 1. Create Gmail Account ──────────────────
  {
    slug: 'create-gmail-account',
    title: 'Create a Gmail Account',
    category: 'communication',
    difficulty: 'medium',
    estimated_minutes: 10,
    is_popular: true,
    tags: ['gmail', 'email', 'google', 'account'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the Google Chrome browser on your phone or computer." },
        simplified_instruction: { en: "Open the browser you use to go to websites." },
        alt_wording: { en: "Find the Chrome or any internet browser app and tap it to open." },
        ui_element_location: 'home screen or app drawer',
        voice_text: { en: "Open the Google Chrome browser on your phone or computer." },
        estimated_seconds: 15,
      },
      {
        step_number: 2,
        instruction: { en: "In the address bar at the top, type 'accounts.google.com' and press Enter." },
        simplified_instruction: { en: "Type the website address at the top of the browser and press Enter." },
        alt_wording: { en: "Tap the long bar at the top of the screen, type accounts.google.com, then tap Go." },
        ui_element_location: 'top of browser screen',
        voice_text: { en: "In the address bar at the top, type accounts dot google dot com and press Enter." },
        estimated_seconds: 20,
      },
      {
        step_number: 3,
        instruction: { en: "Tap the blue 'Create account' button in the centre of the page." },
        simplified_instruction: { en: "Tap the button that says 'Create account'." },
        alt_wording: { en: "Look for the words 'Create account' and tap on them." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap the blue Create account button in the centre of the page." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Tap 'For my personal use' from the dropdown menu that appears." },
        simplified_instruction: { en: "Choose 'For my personal use'." },
        alt_wording: { en: "Select the option that says it is for your own personal use." },
        ui_element_location: 'centre of screen, dropdown list',
        voice_text: { en: "Tap For my personal use from the menu that appears." },
        estimated_seconds: 15,
      },
      {
        step_number: 5,
        instruction: { en: "Type your first name in the 'First name' box and your last name in the 'Last name' box, then tap 'Next'." },
        simplified_instruction: { en: "Enter your first and last name, then tap Next." },
        alt_wording: { en: "Write your name in the two boxes shown, then press the Next button." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type your first name and last name in the boxes, then tap Next." },
        estimated_seconds: 30,
      },
      {
        step_number: 6,
        instruction: { en: "Enter your date of birth and select your gender from the dropdown, then tap 'Next'." },
        simplified_instruction: { en: "Fill in your birthday and gender, then tap Next." },
        alt_wording: { en: "Put in the day, month and year you were born, choose your gender, then press Next." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter your date of birth and select your gender, then tap Next." },
        estimated_seconds: 30,
      },
      {
        step_number: 7,
        instruction: { en: "Tap 'Create your own Gmail address', type the email name you want, then tap 'Next'." },
        simplified_instruction: { en: "Choose your email name and tap Next." },
        alt_wording: { en: "Pick the name you want before @gmail.com, type it in, and press Next." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Create your own Gmail address, type the email name you want, then tap Next." },
        estimated_seconds: 30,
      },
      {
        step_number: 8,
        instruction: { en: "Type a password that has at least 8 characters in the 'Password' box, re-type it in 'Confirm' box, then tap 'Next'." },
        simplified_instruction: { en: "Create a password, type it twice, then tap Next." },
        alt_wording: { en: "Make up a secret password, write it in both boxes, then press Next." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type a password in the Password box, type it again in the Confirm box, then tap Next." },
        estimated_seconds: 40,
      },
      {
        step_number: 9,
        instruction: { en: "Add your mobile phone number for account recovery (optional), then tap 'Next'." },
        simplified_instruction: { en: "Enter your phone number if you want, then tap Next." },
        alt_wording: { en: "You can put your mobile number here in case you forget your password. Press Next when done." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Add your mobile phone number for account recovery, then tap Next." },
        estimated_seconds: 25,
      },
      {
        step_number: 10,
        instruction: { en: "Scroll down and tap the blue 'I agree' button to accept Google's terms and finish creating your account." },
        simplified_instruction: { en: "Scroll down and tap 'I agree' to finish." },
        alt_wording: { en: "Move down the page until you see 'I agree', then tap it to complete your account setup." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Scroll down and tap the blue I agree button to finish creating your account." },
        estimated_seconds: 20,
      },
    ],
  },

  // ── 2. WhatsApp Send Message ──────────────────
  {
    slug: 'whatsapp-send-message',
    title: 'Send a Message on WhatsApp',
    category: 'communication',
    difficulty: 'easy',
    estimated_minutes: 5,
    is_popular: true,
    tags: ['whatsapp', 'message', 'chat'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Find the green WhatsApp icon on your phone's home screen and tap it to open." },
        simplified_instruction: { en: "Tap the green WhatsApp icon on your phone." },
        alt_wording: { en: "Look for a green circle with a white telephone on it and tap it." },
        ui_element_location: 'home screen',
        voice_text: { en: "Find the green WhatsApp icon on your home screen and tap it to open." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap the 'Chats' tab at the bottom of the screen if it is not already selected." },
        simplified_instruction: { en: "Tap 'Chats' at the bottom." },
        alt_wording: { en: "At the bottom of the screen, press the option that says Chats." },
        ui_element_location: 'bottom navigation bar',
        voice_text: { en: "Tap the Chats tab at the bottom of the screen." },
        estimated_seconds: 10,
      },
      {
        step_number: 3,
        instruction: { en: "Tap on the name of the person you want to message from your chat list." },
        simplified_instruction: { en: "Tap the person's name you want to message." },
        alt_wording: { en: "Find the person in your list and tap their name to open the conversation." },
        ui_element_location: 'centre of screen, chat list',
        voice_text: { en: "Tap on the name of the person you want to message from your chat list." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Tap the long white text box at the bottom that says 'Message'." },
        simplified_instruction: { en: "Tap the message box at the bottom." },
        alt_wording: { en: "At the bottom of the screen, tap the area where it says Message." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap the long white text box at the bottom that says Message." },
        estimated_seconds: 10,
      },
      {
        step_number: 5,
        instruction: { en: "Type your message using the keyboard that appears on screen." },
        simplified_instruction: { en: "Type what you want to say." },
        alt_wording: { en: "Use the keys on the keyboard to write your message." },
        ui_element_location: 'centre of screen, keyboard',
        voice_text: { en: "Type your message using the keyboard that appears on screen." },
        estimated_seconds: 30,
      },
      {
        step_number: 6,
        instruction: { en: "Tap the green circular send button (arrow icon) at the bottom-right of the screen." },
        simplified_instruction: { en: "Tap the green send button on the right." },
        alt_wording: { en: "Press the green circle with an arrow on the right side to send your message." },
        ui_element_location: 'bottom-right corner',
        voice_text: { en: "Tap the green circular send button at the bottom-right to send your message." },
        estimated_seconds: 10,
      },
      {
        step_number: 7,
        instruction: { en: "You will see two grey ticks next to your message, meaning it was sent successfully." },
        simplified_instruction: { en: "Two grey ticks mean your message was sent." },
        alt_wording: { en: "Look for two small tick marks beside your message — that means it was sent." },
        ui_element_location: 'bottom-right of message bubble',
        voice_text: { en: "Two grey ticks next to your message mean it was sent successfully." },
        estimated_seconds: 10,
      },
    ],
  },

  // ── 3. WhatsApp Make Call ─────────────────────
  {
    slug: 'whatsapp-make-call',
    title: 'Make a Call on WhatsApp',
    category: 'communication',
    difficulty: 'easy',
    estimated_minutes: 4,
    is_popular: true,
    tags: ['whatsapp', 'call', 'video call', 'voice call'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open WhatsApp by tapping the green WhatsApp icon on your home screen." },
        simplified_instruction: { en: "Open WhatsApp on your phone." },
        alt_wording: { en: "Tap the green icon with a white phone to open WhatsApp." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open WhatsApp by tapping the green WhatsApp icon on your home screen." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap on the name of the person you want to call from the 'Chats' list." },
        simplified_instruction: { en: "Tap the person's name you want to call." },
        alt_wording: { en: "Find the person in your chat list and tap their name." },
        ui_element_location: 'centre of screen, chat list',
        voice_text: { en: "Tap on the name of the person you want to call from the Chats list." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Tap the phone icon at the top-right of the screen to make a voice call." },
        simplified_instruction: { en: "Tap the phone icon at the top-right." },
        alt_wording: { en: "Look for a small telephone icon at the top-right corner and tap it." },
        ui_element_location: 'top-right corner',
        voice_text: { en: "Tap the phone icon at the top-right to make a voice call." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Wait while WhatsApp dials the other person. You will hear a ringing sound." },
        simplified_instruction: { en: "Wait for the other person to pick up." },
        alt_wording: { en: "The phone will ring. Wait for the person to answer." },
        ui_element_location: 'centre of screen, call screen',
        voice_text: { en: "Wait while WhatsApp dials the other person. You will hear a ringing sound." },
        estimated_seconds: 20,
      },
      {
        step_number: 5,
        instruction: { en: "When the call connects, speak clearly into the phone's microphone at the bottom." },
        simplified_instruction: { en: "When connected, speak into your phone." },
        alt_wording: { en: "Once the person answers, talk normally into your phone." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "When the call connects, speak clearly into the phone's microphone." },
        estimated_seconds: 60,
      },
      {
        step_number: 6,
        instruction: { en: "To end the call, tap the red circular end-call button at the bottom-centre of the screen." },
        simplified_instruction: { en: "Tap the red button to end the call." },
        alt_wording: { en: "Press the red circle at the bottom of the screen to hang up." },
        ui_element_location: 'bottom-centre of screen',
        voice_text: { en: "To end the call, tap the red circular end-call button at the bottom-centre." },
        estimated_seconds: 10,
      },
    ],
  },

  // ── 4. UPI Send Money ─────────────────────────
  {
    slug: 'upi-send-money',
    title: 'Send Money Using UPI (PhonePe)',
    category: 'payments',
    difficulty: 'medium',
    estimated_minutes: 6,
    is_popular: true,
    tags: ['upi', 'phonepe', 'payment', 'money transfer'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the PhonePe app by tapping the purple PhonePe icon on your home screen." },
        simplified_instruction: { en: "Open the PhonePe app on your phone." },
        alt_wording: { en: "Find the purple icon with 'Pe' written on it and tap it." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the PhonePe app by tapping the purple PhonePe icon on your home screen." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Send Money' from the list of services shown on the home screen." },
        simplified_instruction: { en: "Tap 'Send Money' on the home screen." },
        alt_wording: { en: "Look for the option that says Send Money and tap it." },
        ui_element_location: 'centre of home screen',
        voice_text: { en: "Tap Send Money from the list of services on the home screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Tap 'To Mobile Number' to send money using a phone number." },
        simplified_instruction: { en: "Choose 'To Mobile Number'." },
        alt_wording: { en: "Select the option that lets you send money using a phone number." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap To Mobile Number to send money using a phone number." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Type the 10-digit mobile number of the person you want to send money to, then tap 'Confirm'." },
        simplified_instruction: { en: "Enter the recipient's phone number and tap Confirm." },
        alt_wording: { en: "Type the mobile number carefully and press Confirm." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type the 10-digit mobile number of the person, then tap Confirm." },
        estimated_seconds: 25,
      },
      {
        step_number: 5,
        instruction: { en: "Enter the amount you want to send in the 'Enter Amount' field." },
        simplified_instruction: { en: "Type the amount of money to send." },
        alt_wording: { en: "In the amount box, type the number of rupees you want to transfer." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter the amount you want to send in the Enter Amount field." },
        estimated_seconds: 20,
      },
      {
        step_number: 6,
        instruction: { en: "Tap the green 'Proceed to Pay' button at the bottom of the screen." },
        simplified_instruction: { en: "Tap 'Proceed to Pay' at the bottom." },
        alt_wording: { en: "Press the button at the bottom that says Proceed to Pay." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap the green Proceed to Pay button at the bottom of the screen." },
        estimated_seconds: 10,
      },
      {
        step_number: 7,
        instruction: { en: "Enter your 4-digit or 6-digit UPI PIN when asked, using the keypad shown on screen." },
        simplified_instruction: { en: "Enter your secret UPI PIN." },
        alt_wording: { en: "Type the special PIN number you set for your UPI account." },
        ui_element_location: 'centre of screen, PIN keypad',
        voice_text: { en: "Enter your UPI PIN using the keypad shown on screen." },
        estimated_seconds: 20,
      },
      {
        step_number: 8,
        instruction: { en: "You will see a green tick with 'Payment Successful' confirming the money was sent." },
        simplified_instruction: { en: "A green tick means the payment was successful." },
        alt_wording: { en: "When you see 'Payment Successful' on screen, the money has been sent." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "A green tick with Payment Successful confirms the money was sent." },
        estimated_seconds: 10,
      },
    ],
  },

  // ── 5. IRCTC Book Train ───────────────────────
  {
    slug: 'irctc-book-train',
    title: 'Book a Train Ticket on IRCTC',
    category: 'travel',
    difficulty: 'hard',
    estimated_minutes: 15,
    is_popular: true,
    tags: ['irctc', 'train', 'ticket', 'railway', 'booking'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the IRCTC Rail Connect app (blue icon) on your phone, or go to irctc.co.in in your browser." },
        simplified_instruction: { en: "Open the IRCTC app or website." },
        alt_wording: { en: "Tap the blue IRCTC app icon on your phone to open it." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the IRCTC Rail Connect app on your phone, or visit irctc.co.in." },
        estimated_seconds: 15,
      },
      {
        step_number: 2,
        instruction: { en: "Log in with your IRCTC User ID and Password, then tap the 'Login' button." },
        simplified_instruction: { en: "Enter your IRCTC username and password and tap Login." },
        alt_wording: { en: "Type your IRCTC account details and press Login." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Log in with your IRCTC User ID and Password, then tap Login." },
        estimated_seconds: 30,
      },
      {
        step_number: 3,
        instruction: { en: "Tap 'Book Ticket' or 'Plan My Journey' from the home screen." },
        simplified_instruction: { en: "Tap 'Book Ticket' on the home screen." },
        alt_wording: { en: "Find and press the option for booking a train ticket." },
        ui_element_location: 'centre of home screen',
        voice_text: { en: "Tap Book Ticket or Plan My Journey from the home screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Type your departure city in the 'From' box and your destination city in the 'To' box." },
        simplified_instruction: { en: "Enter your starting city and destination city." },
        alt_wording: { en: "Fill in where you are travelling from and where you want to go." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type your departure city in the From box and your destination city in the To box." },
        estimated_seconds: 30,
      },
      {
        step_number: 5,
        instruction: { en: "Tap the date field and select the date you want to travel using the calendar shown." },
        simplified_instruction: { en: "Choose your travel date from the calendar." },
        alt_wording: { en: "Tap on the date box and pick the day you want to travel." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap the date field and select your travel date from the calendar." },
        estimated_seconds: 20,
      },
      {
        step_number: 6,
        instruction: { en: "Tap the blue 'Search Trains' button." },
        simplified_instruction: { en: "Tap 'Search Trains'." },
        alt_wording: { en: "Press the button that says Search Trains." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap the blue Search Trains button." },
        estimated_seconds: 10,
      },
      {
        step_number: 7,
        instruction: { en: "Scroll through the list of available trains and tap on the train you want to travel by." },
        simplified_instruction: { en: "Choose the train you want from the list." },
        alt_wording: { en: "Look through the trains shown and tap the one you prefer." },
        ui_element_location: 'centre of screen, list',
        voice_text: { en: "Scroll through the list of trains and tap on the one you want." },
        estimated_seconds: 30,
      },
      {
        step_number: 8,
        instruction: { en: "Select the class of travel (e.g. 'Sleeper' or '3A') and tap 'Book Now'." },
        simplified_instruction: { en: "Choose the seat class and tap 'Book Now'." },
        alt_wording: { en: "Pick the type of seat you want, like Sleeper or 3A, and press Book Now." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Select the class of travel and tap Book Now." },
        estimated_seconds: 20,
      },
      {
        step_number: 9,
        instruction: { en: "Enter passenger details: full name, age, and gender for each traveller, then tap 'Continue'." },
        simplified_instruction: { en: "Fill in passenger name, age and gender, then tap Continue." },
        alt_wording: { en: "Write the name, age and gender of each person travelling and press Continue." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter passenger name, age and gender for each traveller, then tap Continue." },
        estimated_seconds: 45,
      },
      {
        step_number: 10,
        instruction: { en: "Review the booking summary shown on screen, then tap 'Proceed to Payment'." },
        simplified_instruction: { en: "Check the details and tap 'Proceed to Payment'." },
        alt_wording: { en: "Read the booking details carefully, then press the payment button." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Review the booking summary, then tap Proceed to Payment." },
        estimated_seconds: 20,
      },
      {
        step_number: 11,
        instruction: { en: "Select a payment method (UPI, debit card, or net banking) and complete the payment." },
        simplified_instruction: { en: "Choose how you want to pay and complete the payment." },
        alt_wording: { en: "Pick your payment option and follow the steps to pay." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Select a payment method and complete the payment." },
        estimated_seconds: 40,
      },
      {
        step_number: 12,
        instruction: { en: "You will see 'Booking Confirmed' with your PNR number. Note down or screenshot the PNR number." },
        simplified_instruction: { en: "Save your PNR number shown on the confirmation screen." },
        alt_wording: { en: "When you see Booking Confirmed, write down the PNR number shown on screen." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Booking Confirmed will appear with your PNR number. Note it down or take a screenshot." },
        estimated_seconds: 20,
      },
    ],
  },

  // ── 6. Book Doctor Appointment ────────────────
  {
    slug: 'book-doctor-appointment',
    title: 'Book a Doctor Appointment Online',
    category: 'health',
    difficulty: 'medium',
    estimated_minutes: 8,
    is_popular: true,
    tags: ['doctor', 'appointment', 'practo', 'health', 'booking'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the Practo app (white icon with a green cross) on your phone." },
        simplified_instruction: { en: "Open the Practo app on your phone." },
        alt_wording: { en: "Find and tap the Practo app — it has a green cross symbol." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the Practo app on your phone." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Find Doctors' on the home screen." },
        simplified_instruction: { en: "Tap 'Find Doctors'." },
        alt_wording: { en: "Press the option that says Find Doctors." },
        ui_element_location: 'centre of home screen',
        voice_text: { en: "Tap Find Doctors on the home screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Type the type of doctor you need (e.g. 'General Physician' or 'Cardiologist') in the search bar at the top." },
        simplified_instruction: { en: "Search for the type of doctor you need." },
        alt_wording: { en: "Write the kind of doctor you want to see in the search box." },
        ui_element_location: 'top of screen, search bar',
        voice_text: { en: "Type the type of doctor you need in the search bar at the top." },
        estimated_seconds: 20,
      },
      {
        step_number: 4,
        instruction: { en: "Scroll through the list of doctors and tap on the doctor you want to consult." },
        simplified_instruction: { en: "Choose a doctor from the list." },
        alt_wording: { en: "Look at the doctors shown and tap on one to see their details." },
        ui_element_location: 'centre of screen, list',
        voice_text: { en: "Scroll through the list and tap on the doctor you want to see." },
        estimated_seconds: 25,
      },
      {
        step_number: 5,
        instruction: { en: "Tap the 'Book Appointment' button on the doctor's profile page." },
        simplified_instruction: { en: "Tap 'Book Appointment'." },
        alt_wording: { en: "Press the button that says Book Appointment." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap the Book Appointment button on the doctor's profile page." },
        estimated_seconds: 15,
      },
      {
        step_number: 6,
        instruction: { en: "Select a suitable date and available time slot from the calendar shown." },
        simplified_instruction: { en: "Choose a date and time for your appointment." },
        alt_wording: { en: "Pick the day and time that works best for you." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Select a date and time slot from the calendar." },
        estimated_seconds: 25,
      },
      {
        step_number: 7,
        instruction: { en: "Enter your name, age, and the reason for your visit, then tap 'Confirm Booking'." },
        simplified_instruction: { en: "Fill in your details and tap 'Confirm Booking'." },
        alt_wording: { en: "Put in your name, age and what you need the doctor for, then confirm." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter your details and reason for visit, then tap Confirm Booking." },
        estimated_seconds: 30,
      },
      {
        step_number: 8,
        instruction: { en: "You will receive a confirmation SMS and the appointment details will appear on screen." },
        simplified_instruction: { en: "Your booking is confirmed. Check your SMS for details." },
        alt_wording: { en: "A message will be sent to your phone confirming the appointment." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Your booking is confirmed. You will receive a confirmation SMS." },
        estimated_seconds: 10,
      },
    ],
  },

  // ── 7. DigiLocker Create Account ──────────────
  {
    slug: 'digilocker-create-account',
    title: 'Create a DigiLocker Account',
    category: 'government',
    difficulty: 'medium',
    estimated_minutes: 8,
    is_popular: false,
    tags: ['digilocker', 'government', 'documents', 'aadhaar'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the DigiLocker app (dark blue icon) on your phone, or visit digilocker.gov.in in your browser." },
        simplified_instruction: { en: "Open the DigiLocker app on your phone." },
        alt_wording: { en: "Find and tap the DigiLocker app — it is dark blue with a white locker symbol." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the DigiLocker app on your phone." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap the 'Sign Up' button on the welcome screen." },
        simplified_instruction: { en: "Tap 'Sign Up'." },
        alt_wording: { en: "Press the button that says Sign Up to create a new account." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap the Sign Up button on the welcome screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Enter your 12-digit Aadhaar number in the box shown." },
        simplified_instruction: { en: "Type your Aadhaar number." },
        alt_wording: { en: "Put in the 12 numbers printed on your Aadhaar card." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter your 12-digit Aadhaar number in the box." },
        estimated_seconds: 25,
      },
      {
        step_number: 4,
        instruction: { en: "Tap 'Next' and then enter the OTP (one-time password) sent to your Aadhaar-linked mobile number." },
        simplified_instruction: { en: "Enter the OTP sent to your mobile and tap Next." },
        alt_wording: { en: "A secret number will be sent to your phone. Type it in and press Next." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Next, then enter the OTP sent to your Aadhaar-linked mobile number." },
        estimated_seconds: 30,
      },
      {
        step_number: 5,
        instruction: { en: "Enter your full name and date of birth as they appear on your Aadhaar card." },
        simplified_instruction: { en: "Enter your name and date of birth from your Aadhaar card." },
        alt_wording: { en: "Write your name and birthday exactly as shown on your Aadhaar card." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter your full name and date of birth as shown on your Aadhaar card." },
        estimated_seconds: 30,
      },
      {
        step_number: 6,
        instruction: { en: "Create a username by typing a unique name (e.g. your name followed by numbers) in the 'Username' box." },
        simplified_instruction: { en: "Choose a username for your account." },
        alt_wording: { en: "Make up a unique name for your account and type it in the Username box." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Create a username by typing a unique name in the Username box." },
        estimated_seconds: 25,
      },
      {
        step_number: 7,
        instruction: { en: "Create a password with at least 8 characters and type it in both the 'Password' and 'Confirm Password' boxes." },
        simplified_instruction: { en: "Set a password and type it twice." },
        alt_wording: { en: "Make a secret password and write it in both password boxes." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Create a password and type it in both the Password and Confirm Password boxes." },
        estimated_seconds: 30,
      },
      {
        step_number: 8,
        instruction: { en: "Tap the 'Submit' button at the bottom of the form." },
        simplified_instruction: { en: "Tap 'Submit'." },
        alt_wording: { en: "Press the Submit button to finish registration." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap the Submit button at the bottom of the form." },
        estimated_seconds: 10,
      },
      {
        step_number: 9,
        instruction: { en: "Your DigiLocker account is created. You will see your account dashboard with your documents section." },
        simplified_instruction: { en: "Your account is ready. You will see your DigiLocker dashboard." },
        alt_wording: { en: "The main DigiLocker screen means your account was created successfully." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Your DigiLocker account is created. You will see your account dashboard." },
        estimated_seconds: 10,
      },
    ],
  },

  // ── 8. DigiLocker Download Aadhaar ────────────
  {
    slug: 'digilocker-download-aadhaar',
    title: 'Download Aadhaar from DigiLocker',
    category: 'government',
    difficulty: 'easy',
    estimated_minutes: 5,
    is_popular: true,
    tags: ['digilocker', 'aadhaar', 'download', 'document'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the DigiLocker app and log in with your username and password." },
        simplified_instruction: { en: "Open DigiLocker and log in." },
        alt_wording: { en: "Tap the DigiLocker app and enter your login details." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the DigiLocker app and log in with your username and password." },
        estimated_seconds: 20,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Issued Documents' from the home screen menu." },
        simplified_instruction: { en: "Tap 'Issued Documents'." },
        alt_wording: { en: "Press the option labelled Issued Documents." },
        ui_element_location: 'centre of home screen',
        voice_text: { en: "Tap Issued Documents from the home screen menu." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Look for 'Aadhaar Card' in the list. If it's not there, tap the '+' button to add it." },
        simplified_instruction: { en: "Find your Aadhaar in the list or tap '+' to add it." },
        alt_wording: { en: "Check if Aadhaar Card is in your list. If not, tap the plus icon to fetch it." },
        ui_element_location: 'centre of screen, list',
        voice_text: { en: "Look for Aadhaar Card in the list. If not there, tap the plus button to add it." },
        estimated_seconds: 20,
      },
      {
        step_number: 4,
        instruction: { en: "Tap on 'Aadhaar Card' to open it and verify it is your correct document." },
        simplified_instruction: { en: "Tap on Aadhaar Card to view it." },
        alt_wording: { en: "Press Aadhaar Card to open and check that it shows your details." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap on Aadhaar Card to open and verify it." },
        estimated_seconds: 15,
      },
      {
        step_number: 5,
        instruction: { en: "Tap the download icon (downward arrow) at the top-right of the Aadhaar document screen." },
        simplified_instruction: { en: "Tap the download arrow at the top-right." },
        alt_wording: { en: "Press the arrow pointing downward at the top-right to save the document." },
        ui_element_location: 'top-right corner',
        voice_text: { en: "Tap the download icon at the top-right of the Aadhaar document screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 6,
        instruction: { en: "The PDF will be saved to your phone. Tap 'Open' to view it or find it in your Downloads folder." },
        simplified_instruction: { en: "Your Aadhaar is saved. Tap Open to view it." },
        alt_wording: { en: "The Aadhaar PDF is now on your phone. You can find it in Downloads." },
        ui_element_location: 'bottom of screen, notification',
        voice_text: { en: "The PDF is saved to your phone. Tap Open to view it." },
        estimated_seconds: 15,
      },
      {
        step_number: 7,
        instruction: { en: "Enter the password to open the PDF — it is the first 4 letters of your name (lowercase) followed by your birth year (e.g. rama1952)." },
        simplified_instruction: { en: "Enter your name's first 4 letters + birth year to open the PDF." },
        alt_wording: { en: "The PDF password is your name's first 4 lowercase letters and the year you were born." },
        ui_element_location: 'centre of screen, PDF viewer',
        voice_text: { en: "Enter the password: first 4 letters of your name in lowercase, then your birth year." },
        estimated_seconds: 25,
      },
    ],
  },

  // ── 9. Book Gas Cylinder ──────────────────────
  {
    slug: 'book-gas-cylinder',
    title: 'Book a Gas Cylinder Online',
    category: 'shopping',
    difficulty: 'easy',
    estimated_minutes: 6,
    is_popular: true,
    tags: ['gas', 'lpg', 'cylinder', 'booking', 'indane', 'hp gas'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the 'HP Gas', 'Indane' or 'Bharat Gas' app for your gas provider, or open the Umang app." },
        simplified_instruction: { en: "Open your gas provider's app or the Umang app." },
        alt_wording: { en: "Find and open the app for the gas company that supplies your cylinder." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open your gas provider app or the Umang app on your phone." },
        estimated_seconds: 15,
      },
      {
        step_number: 2,
        instruction: { en: "Log in with your registered mobile number or consumer ID." },
        simplified_instruction: { en: "Log in with your mobile number or consumer ID." },
        alt_wording: { en: "Enter the phone number or ID linked to your gas connection to log in." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Log in with your registered mobile number or consumer ID." },
        estimated_seconds: 25,
      },
      {
        step_number: 3,
        instruction: { en: "Tap 'Book a Cylinder' or 'New Booking' from the home screen options." },
        simplified_instruction: { en: "Tap 'Book a Cylinder'." },
        alt_wording: { en: "Find and press the option that says Book a Cylinder or New Booking." },
        ui_element_location: 'centre of home screen',
        voice_text: { en: "Tap Book a Cylinder or New Booking from the home screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Confirm your registered delivery address shown on screen is correct." },
        simplified_instruction: { en: "Check that your delivery address is correct." },
        alt_wording: { en: "Make sure the address shown is where you want the cylinder delivered." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Confirm your delivery address shown on screen is correct." },
        estimated_seconds: 15,
      },
      {
        step_number: 5,
        instruction: { en: "Tap 'Confirm Booking' or 'Proceed' to place the booking." },
        simplified_instruction: { en: "Tap 'Confirm Booking'." },
        alt_wording: { en: "Press the Confirm button to finalise your cylinder booking." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap Confirm Booking to place the booking." },
        estimated_seconds: 10,
      },
      {
        step_number: 6,
        instruction: { en: "If asked, choose a payment method and complete payment (or pay cash on delivery)." },
        simplified_instruction: { en: "Pay online or choose cash on delivery." },
        alt_wording: { en: "Select how you want to pay — you can also choose to pay in cash when the cylinder arrives." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Choose a payment method or select cash on delivery." },
        estimated_seconds: 20,
      },
      {
        step_number: 7,
        instruction: { en: "You will see a booking confirmation number on screen. Note it down." },
        simplified_instruction: { en: "Write down the booking confirmation number shown." },
        alt_wording: { en: "Save the booking number shown on screen so you can track your order." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Note down the booking confirmation number shown on screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 8,
        instruction: { en: "You will receive a confirmation SMS with the expected delivery date." },
        simplified_instruction: { en: "Check your SMS for delivery date details." },
        alt_wording: { en: "A message will come to your phone telling you when the cylinder will arrive." },
        ui_element_location: 'phone SMS',
        voice_text: { en: "A confirmation SMS with the delivery date will be sent to your phone." },
        estimated_seconds: 10,
      },
    ],
  },

  // ── 10. Book Cab Using Ola ────────────────────
  {
    slug: 'book-cab-ola',
    title: 'Book a Cab Using Ola',
    category: 'travel',
    difficulty: 'easy',
    estimated_minutes: 5,
    is_popular: true,
    tags: ['ola', 'cab', 'taxi', 'ride', 'travel'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the Ola app (yellow icon with a black car) on your phone." },
        simplified_instruction: { en: "Open the Ola app on your phone." },
        alt_wording: { en: "Tap the yellow Ola icon on your phone to open it." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the Ola app on your phone." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Allow the app to access your location when prompted, so it can detect where you are." },
        simplified_instruction: { en: "Allow location access when asked." },
        alt_wording: { en: "When a pop-up asks about your location, tap Allow so the app knows where you are." },
        ui_element_location: 'centre of screen, permission popup',
        voice_text: { en: "Allow the app to access your location when prompted." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Tap the 'Enter Destination' box at the bottom-centre of the map screen and type where you want to go." },
        simplified_instruction: { en: "Type your destination in the box at the bottom." },
        alt_wording: { en: "Tap the box at the bottom of the map and type the place you are going to." },
        ui_element_location: 'bottom-centre of screen',
        voice_text: { en: "Tap Enter Destination and type where you want to go." },
        estimated_seconds: 25,
      },
      {
        step_number: 4,
        instruction: { en: "Select your destination from the suggestions that appear below the search box." },
        simplified_instruction: { en: "Tap your destination from the suggestions shown." },
        alt_wording: { en: "Choose the correct address from the list of suggestions." },
        ui_element_location: 'centre of screen, suggestions list',
        voice_text: { en: "Select your destination from the suggestions that appear." },
        estimated_seconds: 15,
      },
      {
        step_number: 5,
        instruction: { en: "Choose the type of ride you want (e.g. 'Mini', 'Sedan', 'Auto') by tapping on it." },
        simplified_instruction: { en: "Choose the type of ride." },
        alt_wording: { en: "Pick the cab type you want — Mini is the cheapest option." },
        ui_element_location: 'bottom of screen, ride options',
        voice_text: { en: "Choose the type of ride you want, such as Mini, Sedan, or Auto." },
        estimated_seconds: 20,
      },
      {
        step_number: 6,
        instruction: { en: "Tap the orange 'Book [ride type]' button at the bottom of the screen." },
        simplified_instruction: { en: "Tap the orange Book button." },
        alt_wording: { en: "Press the big orange button to confirm your booking." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap the orange Book button at the bottom of the screen." },
        estimated_seconds: 10,
      },
      {
        step_number: 7,
        instruction: { en: "Wait for a driver to accept your request. You will see the driver's name, photo and vehicle number on screen." },
        simplified_instruction: { en: "Wait for a driver. Their details will appear on screen." },
        alt_wording: { en: "The app will find a driver for you. Once found, you can see their name and car number." },
        ui_element_location: 'bottom of screen, driver card',
        voice_text: { en: "Wait for a driver to accept. Their name and vehicle details will appear on screen." },
        estimated_seconds: 30,
      },
    ],
  },

  // ── 11. Google Maps Directions ────────────────
  {
    slug: 'google-maps-directions',
    title: 'Get Directions on Google Maps',
    category: 'travel',
    difficulty: 'easy',
    estimated_minutes: 4,
    is_popular: true,
    tags: ['google maps', 'directions', 'navigation', 'maps'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open Google Maps by tapping the colourful map pin icon on your phone." },
        simplified_instruction: { en: "Open Google Maps on your phone." },
        alt_wording: { en: "Find and tap the Google Maps icon — it looks like a colourful location pin." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open Google Maps by tapping the colourful map pin icon on your phone." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap the white search bar at the top that says 'Search here' and type your destination." },
        simplified_instruction: { en: "Tap the search bar and type where you want to go." },
        alt_wording: { en: "Press the search bar at the top and write your destination." },
        ui_element_location: 'top of screen, search bar',
        voice_text: { en: "Tap the search bar at the top and type your destination." },
        estimated_seconds: 20,
      },
      {
        step_number: 3,
        instruction: { en: "Tap the correct destination from the list of suggestions that appears." },
        simplified_instruction: { en: "Tap your destination from the list shown." },
        alt_wording: { en: "Choose the right place from the suggestions list." },
        ui_element_location: 'centre of screen, suggestions',
        voice_text: { en: "Tap the correct destination from the suggestions list." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Tap the blue 'Directions' button that appears at the bottom of the screen." },
        simplified_instruction: { en: "Tap the 'Directions' button." },
        alt_wording: { en: "Press the Directions button shown at the bottom of the map." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap the blue Directions button at the bottom of the screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 5,
        instruction: { en: "Choose your transport mode by tapping the car, bus, walking, or auto-rickshaw icon at the top." },
        simplified_instruction: { en: "Choose how you will travel — car, bus, or walking." },
        alt_wording: { en: "Select the icon that matches how you want to travel." },
        ui_element_location: 'top of directions screen',
        voice_text: { en: "Choose your transport mode by tapping the car, bus, or walking icon." },
        estimated_seconds: 15,
      },
      {
        step_number: 6,
        instruction: { en: "Tap the blue 'Start' button at the bottom-centre to begin navigation with voice instructions." },
        simplified_instruction: { en: "Tap 'Start' to begin getting directions." },
        alt_wording: { en: "Press the Start button and the app will guide you with voice directions." },
        ui_element_location: 'bottom-centre of screen',
        voice_text: { en: "Tap the blue Start button to begin navigation with voice instructions." },
        estimated_seconds: 10,
      },
    ],
  },

  // ── 12. YouTube Search and Play ───────────────
  {
    slug: 'youtube-search-play',
    title: 'Search and Play a Video on YouTube',
    category: 'entertainment',
    difficulty: 'easy',
    estimated_minutes: 3,
    is_popular: true,
    tags: ['youtube', 'video', 'watch', 'entertainment'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Tap the red YouTube icon on your phone's home screen or app drawer." },
        simplified_instruction: { en: "Open the YouTube app on your phone." },
        alt_wording: { en: "Find the red icon with a white triangle and tap it to open YouTube." },
        ui_element_location: 'home screen',
        voice_text: { en: "Tap the red YouTube icon on your phone to open it." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap the magnifying glass search icon at the top-right of the YouTube home screen." },
        simplified_instruction: { en: "Tap the search icon at the top-right." },
        alt_wording: { en: "Press the small magnifying glass icon you can see at the top-right corner." },
        ui_element_location: 'top-right corner',
        voice_text: { en: "Tap the magnifying glass search icon at the top-right." },
        estimated_seconds: 10,
      },
      {
        step_number: 3,
        instruction: { en: "Type what you want to watch (e.g. 'bhajans' or 'yoga for seniors') and tap the Search key on the keyboard." },
        simplified_instruction: { en: "Type what you want to watch and press Search." },
        alt_wording: { en: "Write the name of what you want to watch, then press the Search or Enter key." },
        ui_element_location: 'top of screen, search box',
        voice_text: { en: "Type what you want to watch and tap the Search key on the keyboard." },
        estimated_seconds: 25,
      },
      {
        step_number: 4,
        instruction: { en: "Scroll through the video results and tap on the thumbnail (picture) of the video you want to watch." },
        simplified_instruction: { en: "Tap the video you want to watch." },
        alt_wording: { en: "Look through the videos shown and press on the picture of the one you like." },
        ui_element_location: 'centre of screen, video list',
        voice_text: { en: "Scroll and tap the thumbnail of the video you want to watch." },
        estimated_seconds: 20,
      },
      {
        step_number: 5,
        instruction: { en: "The video will start playing automatically. Tap the screen once to show the pause button if you need to stop." },
        simplified_instruction: { en: "The video plays automatically. Tap the screen to pause." },
        alt_wording: { en: "Your video will start on its own. Tap the screen and then the pause button to stop it." },
        ui_element_location: 'centre of screen, video player',
        voice_text: { en: "The video will start playing. Tap the screen once to show the pause button." },
        estimated_seconds: 10,
      },
    ],
  },

  // ── 13. Join Zoom Meeting ─────────────────────
  {
    slug: 'join-zoom-meeting',
    title: 'Join a Zoom Meeting',
    category: 'communication',
    difficulty: 'medium',
    estimated_minutes: 5,
    is_popular: false,
    tags: ['zoom', 'meeting', 'video call'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the Zoom app (blue icon with a white video camera) on your phone." },
        simplified_instruction: { en: "Open the Zoom app on your phone." },
        alt_wording: { en: "Find and tap the blue Zoom icon on your phone." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the Zoom app on your phone." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Join a Meeting' on the Zoom welcome screen (you do not need to sign in to join)." },
        simplified_instruction: { en: "Tap 'Join a Meeting'." },
        alt_wording: { en: "Press the Join a Meeting button — you don't need an account." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Join a Meeting on the Zoom welcome screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Type the 9- or 10-digit Meeting ID given to you by the meeting organiser in the 'Meeting ID' box." },
        simplified_instruction: { en: "Enter the Meeting ID you received." },
        alt_wording: { en: "Type the meeting number that was shared with you in the Meeting ID box." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type the Meeting ID given to you in the Meeting ID box." },
        estimated_seconds: 25,
      },
      {
        step_number: 4,
        instruction: { en: "Type your name in the 'Your Name' box so others can see who you are." },
        simplified_instruction: { en: "Enter your name." },
        alt_wording: { en: "Write your name so other people in the meeting can identify you." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type your name in the Your Name box." },
        estimated_seconds: 15,
      },
      {
        step_number: 5,
        instruction: { en: "Tap the blue 'Join Meeting' button." },
        simplified_instruction: { en: "Tap 'Join Meeting'." },
        alt_wording: { en: "Press the Join Meeting button to enter the meeting." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap the blue Join Meeting button." },
        estimated_seconds: 10,
      },
      {
        step_number: 6,
        instruction: { en: "If asked for a passcode, enter the meeting passcode shared by the organiser, then tap 'OK'." },
        simplified_instruction: { en: "Enter the passcode if asked, then tap OK." },
        alt_wording: { en: "Type the meeting password if a box appears, then press OK." },
        ui_element_location: 'centre of screen, popup',
        voice_text: { en: "Enter the meeting passcode if asked, then tap OK." },
        estimated_seconds: 20,
      },
      {
        step_number: 7,
        instruction: { en: "Tap 'Join with Video' and 'Join with Computer Audio' (or 'Call via Device Audio') to enable your camera and microphone." },
        simplified_instruction: { en: "Allow video and audio when asked." },
        alt_wording: { en: "When asked about video and audio, tap to allow both so others can see and hear you." },
        ui_element_location: 'centre of screen, audio/video prompts',
        voice_text: { en: "Tap Join with Video and Join Audio to enable your camera and microphone." },
        estimated_seconds: 15,
      },
    ],
  },

  // ── 14. Join Google Meet ──────────────────────
  {
    slug: 'join-google-meet',
    title: 'Join a Google Meet Call',
    category: 'communication',
    difficulty: 'easy',
    estimated_minutes: 4,
    is_popular: false,
    tags: ['google meet', 'video call', 'meeting'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the Google Meet app (green icon with a white video camera) on your phone." },
        simplified_instruction: { en: "Open Google Meet on your phone." },
        alt_wording: { en: "Find the green Google Meet icon and tap it." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the Google Meet app on your phone." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Join with a code' on the Google Meet home screen." },
        simplified_instruction: { en: "Tap 'Join with a code'." },
        alt_wording: { en: "Press the option that says Join with a code." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Join with a code on the Google Meet home screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Type the meeting code (10-letter code like abc-defg-hij) shared by the meeting organiser." },
        simplified_instruction: { en: "Enter the meeting code you received." },
        alt_wording: { en: "Write the code that was shared with you for the meeting." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type the meeting code shared by the organiser." },
        estimated_seconds: 20,
      },
      {
        step_number: 4,
        instruction: { en: "Tap the blue 'Join' button." },
        simplified_instruction: { en: "Tap 'Join'." },
        alt_wording: { en: "Press the Join button to enter the meeting." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap the blue Join button." },
        estimated_seconds: 10,
      },
      {
        step_number: 5,
        instruction: { en: "You may be placed in a waiting room. Wait until the host admits you to the meeting." },
        simplified_instruction: { en: "Wait for the host to let you in." },
        alt_wording: { en: "You might have to wait a moment until the person who organised the meeting lets you in." },
        ui_element_location: 'centre of screen, waiting screen',
        voice_text: { en: "You may be placed in a waiting room. Wait until the host admits you." },
        estimated_seconds: 30,
      },
      {
        step_number: 6,
        instruction: { en: "Once admitted, ensure your microphone and camera are turned on by checking the icons at the bottom of the call screen." },
        simplified_instruction: { en: "Make sure your mic and camera are on." },
        alt_wording: { en: "Check the mic and camera icons at the bottom. They should not have a line through them." },
        ui_element_location: 'bottom of screen, call controls',
        voice_text: { en: "Once admitted, check that your microphone and camera are turned on." },
        estimated_seconds: 15,
      },
    ],
  },

  // ── 15. Reset Forgotten Password ──────────────
  {
    slug: 'reset-forgotten-password',
    title: 'Reset a Forgotten Password',
    category: 'education',
    difficulty: 'medium',
    estimated_minutes: 6,
    is_popular: true,
    tags: ['password', 'reset', 'forgot password', 'account recovery'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the app or website where you have forgotten your password and tap 'Login'." },
        simplified_instruction: { en: "Go to the login screen of the app or website." },
        alt_wording: { en: "Open the app or website and find the Login button to get to the sign-in screen." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Open the app or website and tap Login to reach the sign-in screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Forgot Password?' which is usually shown below the password box in small text." },
        simplified_instruction: { en: "Tap 'Forgot Password?' below the password box." },
        alt_wording: { en: "Look for small text saying Forgot Password below where you type your password and tap it." },
        ui_element_location: 'below password input field',
        voice_text: { en: "Tap Forgot Password shown below the password box." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Enter your registered email address or mobile number in the box shown." },
        simplified_instruction: { en: "Enter your email or phone number." },
        alt_wording: { en: "Type the email address or mobile number you used when creating the account." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter your registered email address or mobile number." },
        estimated_seconds: 25,
      },
      {
        step_number: 4,
        instruction: { en: "Tap 'Send OTP' or 'Send Reset Link'. An OTP or link will be sent to your phone or email." },
        simplified_instruction: { en: "Tap to receive an OTP or reset link." },
        alt_wording: { en: "Press the button to get a secret code sent to your phone or email." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Send OTP or Send Reset Link to receive a verification code." },
        estimated_seconds: 15,
      },
      {
        step_number: 5,
        instruction: { en: "Check your SMS or email for the OTP (a 4 or 6-digit number) and type it in the box." },
        simplified_instruction: { en: "Enter the OTP from your SMS or email." },
        alt_wording: { en: "A number was sent to your phone or email. Type it in the box on screen." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Check your SMS or email for the OTP and type it in the box." },
        estimated_seconds: 30,
      },
      {
        step_number: 6,
        instruction: { en: "Type your new password in the 'New Password' box and again in 'Confirm Password'." },
        simplified_instruction: { en: "Create and confirm your new password." },
        alt_wording: { en: "Make up a new password and type it in both password boxes." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type your new password in the New Password box and confirm it below." },
        estimated_seconds: 30,
      },
      {
        step_number: 7,
        instruction: { en: "Tap 'Reset Password' or 'Save'. You will now be able to log in with your new password." },
        simplified_instruction: { en: "Tap 'Reset Password' to save your new password." },
        alt_wording: { en: "Press the button to save your new password. You can now log in with it." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap Reset Password to save your new password." },
        estimated_seconds: 15,
      },
    ],
  },

  // ── 16. Pay Electricity Bill ──────────────────
  {
    slug: 'pay-electricity-bill',
    title: 'Pay Electricity Bill Online',
    category: 'payments',
    difficulty: 'medium',
    estimated_minutes: 6,
    is_popular: true,
    tags: ['electricity', 'bill payment', 'upi', 'phonepe', 'paytm'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the PhonePe, Paytm, or Google Pay app on your phone." },
        simplified_instruction: { en: "Open a payments app like PhonePe or Paytm." },
        alt_wording: { en: "Tap the PhonePe, Paytm, or Google Pay icon on your phone." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the PhonePe, Paytm, or Google Pay app on your phone." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Recharge & Pay Bills' or 'Electricity' from the home screen services." },
        simplified_instruction: { en: "Tap 'Electricity' on the home screen." },
        alt_wording: { en: "Look for the Electricity option in the bills or services section." },
        ui_element_location: 'centre of home screen',
        voice_text: { en: "Tap Recharge and Pay Bills or Electricity from the home screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Tap 'Electricity' from the bill payment categories." },
        simplified_instruction: { en: "Select 'Electricity'." },
        alt_wording: { en: "From the list of bill types, choose Electricity." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Electricity from the bill payment categories." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Select your electricity provider/board from the list (e.g. BESCOM, MSEDCL, TNEB)." },
        simplified_instruction: { en: "Choose your electricity provider from the list." },
        alt_wording: { en: "Find your electricity board's name in the list and tap it." },
        ui_element_location: 'centre of screen, provider list',
        voice_text: { en: "Select your electricity provider from the list." },
        estimated_seconds: 20,
      },
      {
        step_number: 5,
        instruction: { en: "Enter your Consumer Number or Account Number printed on your electricity bill, then tap 'Fetch Bill'." },
        simplified_instruction: { en: "Enter your consumer number from your bill and tap 'Fetch Bill'." },
        alt_wording: { en: "Type the number printed on your electricity bill and press Fetch Bill." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter your Consumer Number from your electricity bill, then tap Fetch Bill." },
        estimated_seconds: 30,
      },
      {
        step_number: 6,
        instruction: { en: "Verify the bill amount shown on screen matches your actual bill." },
        simplified_instruction: { en: "Check that the amount matches your bill." },
        alt_wording: { en: "Make sure the amount shown is the same as what your electricity bill says." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Verify the bill amount shown matches your electricity bill." },
        estimated_seconds: 15,
      },
      {
        step_number: 7,
        instruction: { en: "Tap 'Pay Now' or 'Proceed to Pay' at the bottom of the screen." },
        simplified_instruction: { en: "Tap 'Pay Now'." },
        alt_wording: { en: "Press the Pay Now button to go to the payment screen." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap Pay Now at the bottom of the screen." },
        estimated_seconds: 10,
      },
      {
        step_number: 8,
        instruction: { en: "Enter your UPI PIN or complete the payment through your selected payment method. You will see 'Payment Successful' on completion." },
        simplified_instruction: { en: "Enter your PIN to complete the payment." },
        alt_wording: { en: "Type your UPI PIN to pay. You will see a success message when done." },
        ui_element_location: 'centre of screen, payment screen',
        voice_text: { en: "Enter your UPI PIN to complete the payment. You will see Payment Successful when done." },
        estimated_seconds: 25,
      },
    ],
  },

  // ── 17. Recharge Mobile ───────────────────────
  {
    slug: 'recharge-mobile',
    title: 'Recharge Your Mobile Number',
    category: 'payments',
    difficulty: 'easy',
    estimated_minutes: 4,
    is_popular: true,
    tags: ['recharge', 'mobile', 'prepaid', 'phonepe', 'paytm'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the PhonePe or Paytm app on your phone." },
        simplified_instruction: { en: "Open PhonePe or Paytm." },
        alt_wording: { en: "Tap the PhonePe or Paytm icon to open the app." },
        ui_element_location: 'home screen',
        voice_text: { en: "Open the PhonePe or Paytm app on your phone." },
        estimated_seconds: 10,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Mobile Recharge' from the home screen options." },
        simplified_instruction: { en: "Tap 'Mobile Recharge'." },
        alt_wording: { en: "Find and press Mobile Recharge on the home screen." },
        ui_element_location: 'centre of home screen',
        voice_text: { en: "Tap Mobile Recharge from the home screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Type your 10-digit mobile number in the 'Enter Mobile Number' box." },
        simplified_instruction: { en: "Enter your mobile number." },
        alt_wording: { en: "Type your 10-digit phone number carefully in the box." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Type your 10-digit mobile number in the box." },
        estimated_seconds: 20,
      },
      {
        step_number: 4,
        instruction: { en: "Your mobile operator (Jio, Airtel, Vi, BSNL) will be auto-detected. Confirm it is correct." },
        simplified_instruction: { en: "Check your operator name is correct." },
        alt_wording: { en: "The app will show your network operator. Make sure it shows the correct one." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Your mobile operator will be auto-detected. Confirm it is correct." },
        estimated_seconds: 10,
      },
      {
        step_number: 5,
        instruction: { en: "Select a recharge plan by tapping on it. Plans show validity and data details." },
        simplified_instruction: { en: "Choose a recharge plan." },
        alt_wording: { en: "Look at the plans shown and tap the one you want to recharge with." },
        ui_element_location: 'centre of screen, plan list',
        voice_text: { en: "Select a recharge plan by tapping on it." },
        estimated_seconds: 20,
      },
      {
        step_number: 6,
        instruction: { en: "Tap 'Proceed to Pay', enter your UPI PIN, and wait for the 'Recharge Successful' confirmation." },
        simplified_instruction: { en: "Tap Proceed to Pay, enter your PIN. Recharge will be successful." },
        alt_wording: { en: "Press Proceed to Pay, type your PIN, and you will see a success message once done." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap Proceed to Pay, enter your UPI PIN. You will see Recharge Successful when done." },
        estimated_seconds: 25,
      },
    ],
  },

  // ── 18. Book Vaccination Slot ─────────────────
  {
    slug: 'book-vaccination-slot',
    title: 'Book a Vaccination Slot Online',
    category: 'health',
    difficulty: 'medium',
    estimated_minutes: 8,
    is_popular: false,
    tags: ['vaccination', 'cowin', 'covid', 'health', 'booking'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open the CoWIN app or go to cowin.gov.in in your browser." },
        simplified_instruction: { en: "Open the CoWIN app or website." },
        alt_wording: { en: "Find the CoWIN app on your phone or type cowin.gov.in in your browser." },
        ui_element_location: 'home screen or browser',
        voice_text: { en: "Open the CoWIN app or visit cowin.gov.in in your browser." },
        estimated_seconds: 15,
      },
      {
        step_number: 2,
        instruction: { en: "Tap 'Register / Sign In Yourself' on the CoWIN home screen." },
        simplified_instruction: { en: "Tap 'Register / Sign In'." },
        alt_wording: { en: "Press the button to register or sign in on the first screen." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Register or Sign In Yourself on the CoWIN home screen." },
        estimated_seconds: 15,
      },
      {
        step_number: 3,
        instruction: { en: "Enter your 10-digit mobile number and tap 'Get OTP'." },
        simplified_instruction: { en: "Enter your phone number and tap 'Get OTP'." },
        alt_wording: { en: "Type your mobile number and press Get OTP to receive a verification code." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter your 10-digit mobile number and tap Get OTP." },
        estimated_seconds: 20,
      },
      {
        step_number: 4,
        instruction: { en: "Enter the 6-digit OTP received on your phone and tap 'Verify OTP'." },
        simplified_instruction: { en: "Enter the OTP from your SMS and tap 'Verify OTP'." },
        alt_wording: { en: "Type the 6-digit number sent to your phone and press Verify OTP." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter the 6-digit OTP from your SMS and tap Verify OTP." },
        estimated_seconds: 25,
      },
      {
        step_number: 5,
        instruction: { en: "Add a beneficiary by tapping 'Add Member' and filling in the name, age, ID type (Aadhaar) and ID number." },
        simplified_instruction: { en: "Add the person to be vaccinated with their Aadhaar details." },
        alt_wording: { en: "Tap Add Member, then enter the name, age and Aadhaar number of the person getting vaccinated." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Add Member and fill in the name, age and Aadhaar number." },
        estimated_seconds: 40,
      },
      {
        step_number: 6,
        instruction: { en: "Tap 'Schedule Appointment' next to the beneficiary's name." },
        simplified_instruction: { en: "Tap 'Schedule Appointment'." },
        alt_wording: { en: "Press Schedule Appointment to find available vaccine slots." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Tap Schedule Appointment next to the beneficiary's name." },
        estimated_seconds: 15,
      },
      {
        step_number: 7,
        instruction: { en: "Enter your pin code and tap 'Search' to find nearby vaccination centres." },
        simplified_instruction: { en: "Enter your pin code and tap Search." },
        alt_wording: { en: "Type your area's pin code and press Search to find vaccination centres near you." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter your pin code and tap Search to find nearby vaccination centres." },
        estimated_seconds: 20,
      },
      {
        step_number: 8,
        instruction: { en: "Select an available date and time slot at a centre near you." },
        simplified_instruction: { en: "Choose a date and time slot." },
        alt_wording: { en: "Pick a convenient date and available time from the slots shown." },
        ui_element_location: 'centre of screen, slot calendar',
        voice_text: { en: "Select an available date and time slot at a centre near you." },
        estimated_seconds: 25,
      },
      {
        step_number: 9,
        instruction: { en: "Tap 'Confirm' to book the slot. A booking confirmation will appear on screen and be sent as an SMS." },
        simplified_instruction: { en: "Tap 'Confirm' to complete your booking." },
        alt_wording: { en: "Press Confirm. You will see a confirmation and also receive an SMS." },
        ui_element_location: 'bottom of screen',
        voice_text: { en: "Tap Confirm to book the slot. A confirmation will appear and be sent by SMS." },
        estimated_seconds: 15,
      },
    ],
  },

  // ── 19. Apply for Pension (EPFO) ──────────────
  {
    slug: 'apply-for-pension',
    title: 'Apply for Pension Online (EPFO)',
    category: 'government',
    difficulty: 'hard',
    estimated_minutes: 15,
    is_popular: false,
    tags: ['pension', 'epfo', 'pf', 'government', 'retirement'],
    steps: [
      {
        step_number: 1,
        instruction: { en: "Open your browser and go to the EPFO member portal: unifiedportal-mem.epfindia.gov.in" },
        simplified_instruction: { en: "Open the EPFO website in your browser." },
        alt_wording: { en: "Type the EPFO website address in your browser's address bar and press Enter." },
        ui_element_location: 'browser address bar',
        voice_text: { en: "Open your browser and go to the EPFO member portal website." },
        estimated_seconds: 20,
      },
      {
        step_number: 2,
        instruction: { en: "Enter your UAN (Universal Account Number), password and captcha code, then tap 'Sign In'." },
        simplified_instruction: { en: "Enter your UAN and password, then tap Sign In." },
        alt_wording: { en: "Type your 12-digit UAN number, your password, and the code shown on screen, then press Sign In." },
        ui_element_location: 'centre of screen, login form',
        voice_text: { en: "Enter your UAN, password and captcha, then tap Sign In." },
        estimated_seconds: 40,
      },
      {
        step_number: 3,
        instruction: { en: "Click on the 'Online Services' menu at the top of the page." },
        simplified_instruction: { en: "Click 'Online Services' at the top." },
        alt_wording: { en: "Find the Online Services option in the menu bar at the top and click it." },
        ui_element_location: 'top navigation menu',
        voice_text: { en: "Click on Online Services at the top of the page." },
        estimated_seconds: 15,
      },
      {
        step_number: 4,
        instruction: { en: "Select 'Claim (Form-31, 19, 10C & 10D)' from the dropdown menu." },
        simplified_instruction: { en: "Select the Claim option from the dropdown." },
        alt_wording: { en: "From the list that appears, choose Claim (Form-31, 19, 10C & 10D)." },
        ui_element_location: 'top dropdown menu',
        voice_text: { en: "Select Claim Form-31, 19, 10C and 10D from the dropdown menu." },
        estimated_seconds: 15,
      },
      {
        step_number: 5,
        instruction: { en: "Verify your bank account details shown on screen are correct, then tap 'Proceed for Online Claim'." },
        simplified_instruction: { en: "Check your bank details and tap 'Proceed for Online Claim'." },
        alt_wording: { en: "Make sure the bank account shown is correct, then press Proceed for Online Claim." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Verify your bank account details, then tap Proceed for Online Claim." },
        estimated_seconds: 25,
      },
      {
        step_number: 6,
        instruction: { en: "Select 'Pension Withdrawal Benefit (EPS Scheme Certificate / Scheme Certificate)' from the claim type dropdown." },
        simplified_instruction: { en: "Choose the Pension Withdrawal option from the dropdown." },
        alt_wording: { en: "From the claim type list, select the pension withdrawal benefit option." },
        ui_element_location: 'centre of screen, claim type dropdown',
        voice_text: { en: "Select Pension Withdrawal Benefit from the claim type dropdown." },
        estimated_seconds: 20,
      },
      {
        step_number: 7,
        instruction: { en: "Fill in your address, reason for leaving service, and last working date in the fields shown." },
        simplified_instruction: { en: "Fill in your address and last working date." },
        alt_wording: { en: "Enter the required details including your address and the date you stopped working." },
        ui_element_location: 'centre of screen, form fields',
        voice_text: { en: "Fill in your address, reason for leaving, and last working date." },
        estimated_seconds: 60,
      },
      {
        step_number: 8,
        instruction: { en: "Upload a scanned copy or clear photo of your cancelled cheque in the 'Upload Cheque' section." },
        simplified_instruction: { en: "Upload a photo of your cancelled cheque." },
        alt_wording: { en: "Take a clear photo of a cancelled cheque from your bank account and upload it here." },
        ui_element_location: 'centre of screen, upload section',
        voice_text: { en: "Upload a scanned copy or photo of your cancelled cheque." },
        estimated_seconds: 40,
      },
      {
        step_number: 9,
        instruction: { en: "Tick the declaration checkbox at the bottom of the form and tap 'Get Aadhaar OTP'." },
        simplified_instruction: { en: "Tick the checkbox and tap 'Get Aadhaar OTP'." },
        alt_wording: { en: "Check the small box for the declaration, then press Get Aadhaar OTP." },
        ui_element_location: 'bottom of form',
        voice_text: { en: "Tick the declaration checkbox and tap Get Aadhaar OTP." },
        estimated_seconds: 20,
      },
      {
        step_number: 10,
        instruction: { en: "Enter the OTP sent to your Aadhaar-linked mobile number and tap 'Validate OTP and Submit Claim Form'." },
        simplified_instruction: { en: "Enter the OTP and tap to submit your claim." },
        alt_wording: { en: "Type the code sent to your mobile and press Validate OTP and Submit to complete your application." },
        ui_element_location: 'centre of screen',
        voice_text: { en: "Enter the OTP from your mobile and tap Validate OTP and Submit Claim Form." },
        estimated_seconds: 30,
      },
    ],
  },
]

// ─────────────────────────────────────────────
// SEED FUNCTION
// ─────────────────────────────────────────────

async function seedGuides () {
  console.log(`Starting seed — ${guides.length} guides to insert…`)

  for (const guide of guides) {
    const { steps, ...guideData } = guide

    // Upsert guide on slug
    const { data: upserted, error: guideErr } = await supabase
      .from('guides')
      .upsert(guideData, { onConflict: 'slug' })
      .select('id, slug')
      .single()

    if (guideErr) {
      console.error(`✗ Failed to upsert guide "${guide.slug}":`, guideErr.message)
      continue
    }

    const guideId = upserted.id
    console.log(`✓ Guide upserted: ${upserted.slug} (${guideId})`)

    // Delete existing steps for idempotency
    const { error: delErr } = await supabase
      .from('guide_steps')
      .delete()
      .eq('guide_id', guideId)

    if (delErr) {
      console.error(`  ✗ Failed to delete old steps for "${guide.slug}":`, delErr.message)
      continue
    }

    // Bulk insert fresh steps
    const stepsToInsert = steps.map(step => ({
      ...step,
      guide_id: guideId,
    }))

    const { error: stepsErr } = await supabase
      .from('guide_steps')
      .insert(stepsToInsert)

    if (stepsErr) {
      console.error(`  ✗ Failed to insert steps for "${guide.slug}":`, stepsErr.message)
    } else {
      console.log(`  ✓ ${steps.length} steps inserted for "${guide.slug}"`)
    }
  }

  console.log('\nSeed complete.')
}

seedGuides().catch(err => {
  console.error('Seed script failed:', err)
  process.exit(1)
})
